version: '3.4'

services:
  web:
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Lab2.Web/Dockerfile
    image: lab2-web
    depends_on:
      - worker

  worker:
    build:
      context: .
      dockerfile: Lab2.Worker/Dockerfile
    image: lab2-worker
    restart: always
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: public.ecr.aws/docker/library/mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "knifes"
    ports:
      - "3306:3306"
    depends_on:
      - phpmyadmin

  phpmyadmin:
    image: phpmyadmin:5.2.0
    restart: always
    ports:
      - 5013:80
    environment:
      - PMA_ARBITRARY=1

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    labels:
        NAME: "rabbitmq"
    ports:
        - "5672:5672"
        - "15672:15672"